# Generated by Django 3.2.7 on 2021-09-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.URLField()),
                ('yt', models.URLField()),
                ('doc', models.URLField()),
                ('devname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.devname')),
            ],
        ),
    ]
