# Generated by Django 3.2.7 on 2021-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210923_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external',
            name='book',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='external',
            name='doc',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='external',
            name='yt',
            field=models.URLField(blank=True),
        ),
    ]
