# Generated by Django 3.2.7 on 2021-09-24 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='devname',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.devname'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
